version: "2.4"

services:
  www:
    environment:
      LAPIS_ENV: production
    mem_limit: 50mb
    memswap_limit: 50mb
    build:
      context: ./
      dockerfile: Dockerfile
    image: darltrash/lapis-rocky:latest
    volumes:
      - ./www:/var/www
      - ./data:/var/data
    ports:
      - 8080:80
    restart: always
    command: bash -c "/usr/local/bin/docker-entrypoint.sh"
